# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: plympton 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "plympton"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roger Seagle"]
  s.date = "2014-10-09"
  s.description = "A Gem to read program disassembly from a YAML dump.  The YAML dump is generated from an ida pro python script.  This script is included along with this Gem (func.py)"
  s.email = "roger.seagle@gmail.com"
  s.executables = ["func-auto.py", "func.py", "func.py.new", "idascript.py"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/func-auto.py",
    "bin/func.py",
    "bin/func.py.new",
    "bin/idascript.py",
    "lib/plympton.rb",
    "lib/plympton/Solver.tokens",
    "lib/plympton/SolverLexer.rb",
    "lib/plympton/SolverParser.rb",
    "lib/plympton/block.rb",
    "lib/plympton/chunk.rb",
    "lib/plympton/disassembly.rb",
    "lib/plympton/function.rb",
    "lib/plympton/matrix.rb",
    "lib/plympton/object.rb",
    "lib/plympton/solver.g",
    "spec/libFontParser.64.dylib.fz",
    "spec/libauto.dylib.fz",
    "spec/plympton_spec.rb",
    "spec/rufus-test.32bit.trace.xml",
    "spec/rufus-test.64bit.trace.xml",
    "spec/spec_helper.rb",
    "spec/steady-state.64bit.trace.xml"
  ]
  s.homepage = "http://github.com/rogwfu/plympton"
  s.licenses = ["MIT"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.3")
  s.rubygems_version = "2.2.2"
  s.summary = "Reads a YAML dump of a program's disassembly from IDA Pro"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_runtime_dependency(%q<antlr3>, ["~> 1.10"])
      s.add_runtime_dependency(%q<narray>, ["~> 0.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.7"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_dependency(%q<antlr3>, ["~> 1.10"])
      s.add_dependency(%q<narray>, ["~> 0.6"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<bundler>, ["~> 1.7"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.6"])
    s.add_dependency(%q<antlr3>, ["~> 1.10"])
    s.add_dependency(%q<narray>, ["~> 0.6"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<bundler>, ["~> 1.7"])
  end
end

